# Generated by Django 3.1 on 2022-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220304_1722'),
        ('service_contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecontract',
            name='experts',
        ),
        migrations.AddField(
            model_name='servicecontract',
            name='sup_visor',
            field=models.ManyToManyField(related_name='contracts', to='accounts.SupVsProfile'),
        ),
    ]
