# Generated by Django 3.1 on 2022-03-07 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_contract', '0002_auto_20220307_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='order_num',
            field=models.CharField(default=uuid.UUID('3633be91-5958-4c71-a501-d221048b03e4'), max_length=100),
        ),
    ]
