# Generated by Django 3.1 on 2022-03-07 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_contract', '0003_auto_20220307_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='order_num',
            field=models.CharField(default=uuid.UUID('3d19f4c3-7527-442f-80ca-bdf2d92f2e2e'), max_length=100),
        ),
    ]
