# Generated by Django 3.1 on 2022-03-08 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business_skill', '0003_validskill_tag'),
        ('service_contract', '0004_auto_20220307_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontract',
            name='skill',
            field=models.ManyToManyField(related_name='contracts', to='business_skill.ValidSkill'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='order_num',
            field=models.CharField(default=uuid.UUID('a8f7ee69-1fc7-4000-b23d-c52fb29c6f61'), max_length=100),
        ),
    ]
