# Generated by Django 3.1 on 2022-03-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_contract', '0006_remove_servicecontract_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecontract',
            name='skill',
        ),
    ]
