# Generated by Django 3.1 on 2022-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_contract', '0007_remove_servicecontract_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
