# Generated by Django 3.1 on 2022-03-08 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220306_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('registered_count', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('off_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('off_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_order_services', to='accounts.businessprofile')),
                ('user_register', models.ManyToManyField(related_name='pre_order_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
