# Generated by Django 3.1 on 2022-03-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('note', models.CharField(max_length=300)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attrs', to='pre_order_service.preorderservice')),
            ],
        ),
    ]
