# Generated by Django 3.1 on 2022-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order_service', '0002_serviceattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderservice',
            name='off_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
