# Generated by Django 3.1 on 2022-02-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_businessprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('selected_number', models.PositiveIntegerField(default=0)),
                ('admin_data_confirm', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='valid_skill', to='accounts.admindataconfirm')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_skills', to='accounts.businessprofile')),
                ('valid_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_skills', to='business_service.validskill')),
            ],
            options={
                'unique_together': {('valid_skill', 'business_profile')},
            },
        ),
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('max_step_number', models.PositiveIntegerField(default=0)),
                ('total_up_votes', models.PositiveIntegerField(default=0)),
                ('admin_data_confirm', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_products', to='accounts.admindataconfirm')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='accounts.businessprofile')),
                ('business_skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_products', to='business_service.businessskill')),
            ],
            options={
                'unique_together': {('title', 'business_profile')},
            },
        ),
    ]
