# Generated by Django 3.1 on 2022-03-05 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('max_step_number', models.PositiveIntegerField(default=0)),
                ('total_up_votes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProductStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('step_url', models.URLField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('step_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProductVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=299, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('least_budget', models.PositiveIntegerField()),
                ('max_budget', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField(null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_note', models.CharField(max_length=300)),
            ],
        ),
    ]
