# Generated by Django 3.1 on 2022-02-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('selected_number', models.PositiveIntegerField(default=0)),
                ('admin_data_confirm', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='valid_skills', to='accounts.admindataconfirm')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_skills', to='accounts.businessprofile')),
                ('valid_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_skills', to='business_service.validskill')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('step', models.IntegerField(blank=True, null=True)),
                ('admin_score', models.IntegerField(blank=True, null=True)),
                ('admin_data_confirm', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_product', to='accounts.admindataconfirm')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='accounts.businessprofile')),
                ('business_skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_products', to='business_service.businessskill')),
            ],
        ),
    ]
