# Generated by Django 3.1 on 2022-02-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220210_1642'),
        ('business_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessproduct',
            old_name='admin_score',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='validskill',
            name='admin_data_confirm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='valid_skill', to='accounts.admindataconfirm'),
        ),
    ]
