# Generated by Django 3.1 on 2022-02-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProductVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=299, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('business_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_votes', to='business_service.businessproduct')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_votes', to='accounts.personalprofile')),
            ],
        ),
    ]
