# Generated by Django 3.1 on 2022-03-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_contract', '0001_initial'),
        ('business_skill', '0001_initial'),
        ('business_service', '0001_initial'),
        ('accounts', '0002_auto_20220312_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='service_contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_review', to='service_contract.servicecontract'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_review', to='business_service.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestbid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_bids', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='servicerequestbid',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_bids', to='business_service.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='receiver',
            field=models.ManyToManyField(related_name='service_requests', to='accounts.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.personalprofile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='skill',
            field=models.ManyToManyField(related_name='service_requests', to='business_skill.ValidSkill'),
        ),
        migrations.AddField(
            model_name='businessproductvote',
            name='business_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_votes', to='business_service.businessproduct'),
        ),
        migrations.AddField(
            model_name='businessproductvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_votes', to='accounts.personalprofile'),
        ),
        migrations.AddField(
            model_name='businessproductstep',
            name='business_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_steps', to='business_service.businessproduct'),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='business_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_products', to='business_skill.businessskill'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestbid',
            unique_together={('bidder', 'service_request')},
        ),
        migrations.AlterUniqueTogether(
            name='businessproduct',
            unique_together={('title', 'business_profile')},
        ),
    ]
