# Generated by Django 3.1 on 2022-02-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('note', models.TextField()),
                ('education_institute_name', models.CharField(max_length=150)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_specialties', to='accounts.businessprofile')),
            ],
            options={
                'unique_together': {('business_profile', 'title')},
            },
        ),
    ]
