# Generated by Django 3.1 on 2022-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0002_auto_20220306_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='least_budget',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='max_budget',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='max_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='min_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
