# Generated by Django 3.1 on 2022-02-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0002_remove_contractassign_admin_conf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('payment_service', models.CharField(max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='business_service.servicecontract')),
            ],
        ),
    ]
