# Generated by Django 3.1 on 2022-03-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0002_auto_20220302_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='receivers',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='skills',
            new_name='skill',
        ),
    ]
