# Generated by Django 3.1 on 2022-02-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_service', '0002_businessproductvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproduct',
            name='business_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_products', to='business_service.businessskill'),
        ),
    ]
