# Generated by Django 3.1 on 2022-02-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admindataconfirm_comment'),
        ('business_service', '0003_auto_20220215_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('least_budget', models.PositiveIntegerField()),
                ('max_budget', models.PositiveIntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.personalprofile')),
                ('valid_skills', models.ManyToManyField(related_name='service_requests', to='business_service.ValidSkill')),
            ],
        ),
    ]
