# Generated by Django 3.1 on 2022-03-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expertprofile'),
        ('business_service', '0003_contractfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='experts',
            field=models.ManyToManyField(related_name='contracts', to='accounts.ExpertProfile'),
        ),
        migrations.DeleteModel(
            name='ContractFactor',
        ),
    ]
