# Generated by Django 3.1 on 2022-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admindataconfirm_comment'),
        ('business_service', '0004_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='valid_skills',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='receivers',
            field=models.ManyToManyField(null=True, related_name='service_requests', to='accounts.BusinessProfile'),
        ),
    ]
