# Generated by Django 3.1 on 2022-02-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admindataconfirm_comment'),
        ('business_service', '0005_auto_20220216_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='receivers',
            field=models.ManyToManyField(related_name='service_requests', to='accounts.BusinessProfile'),
        ),
    ]
