# Generated by Django 3.1 on 2022-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admindataconfirm_comment'),
        ('business_service', '0006_auto_20220217_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='acceptors',
            field=models.ManyToManyField(related_name='accepted_service_requests', to='accounts.BusinessProfile'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='receivers',
            field=models.ManyToManyField(related_name='received_service_requests', to='accounts.BusinessProfile'),
        ),
    ]
