# Generated by Django 3.1 on 2022-02-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admindataconfirm_comment'),
        ('business_service', '0008_auto_20220217_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='receivers',
            field=models.ManyToManyField(related_name='service_requests', to='accounts.BusinessProfile'),
        ),
    ]
