# Generated by Django 3.1 on 2022-02-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admindataconfirm_comment'),
        ('business_service', '0011_auto_20220218_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_contract', to='business_service.servicerequestbid')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='accounts.businessprofile')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_contract', to='business_service.servicerequest')),
            ],
        ),
    ]
