# Generated by Django 3.1 on 2022-02-24 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        ('business_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='skills',
            field=models.ManyToManyField(related_name='admin_profiles', to='business_service.ValidSkill'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admindataconfirm',
            name='admin_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_data_confirms', to='accounts.adminprofile'),
        ),
        migrations.AddField(
            model_name='admindataconfirm',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_data_confirms', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='admindataconfirm',
            name='target_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='contenttypes.contenttype'),
        ),
    ]
