# Generated by Django 3.1 on 2022-02-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='confirmed_data_number',
            new_name='checked_data_number',
        ),
    ]
