# Generated by Django 3.1 on 2022-03-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0002_auto_20220302_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdataconfirm',
            name='target_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conf_obj', to='contenttypes.contenttype'),
        ),
    ]
