# Generated by Django 3.1 on 2022-02-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0002_auto_20220224_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminDataConfirm',
            new_name='SystemDataConfirm',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='skills',
        ),
    ]
