# Generated by Django 3.1 on 2022-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220306_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='service_rate',
            field=models.FloatField(default=0),
        ),
    ]
