# Generated by Django 3.1 on 2022-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220210_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
