# Generated by Django 3.1 on 2022-02-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220215_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindataconfirm',
            name='comment',
        ),
    ]
