# Generated by Django 3.1 on 2022-03-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220303_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertprofile',
            old_name='skills',
            new_name='skill',
        ),
    ]
