# Generated by Django 3.1 on 2022-02-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220211_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
