# Generated by Django 3.1 on 2022-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_admindataconfirm_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindataconfirm',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
