# Generated by Django 3.1 on 2022-03-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('selected_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('note', models.TextField()),
                ('education_institute_name', models.CharField(max_length=150)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_specialties', to='accounts.businessprofile')),
            ],
            options={
                'unique_together': {('business_profile', 'title')},
            },
        ),
        migrations.CreateModel(
            name='BusinessSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_skills', to='accounts.businessprofile')),
                ('valid_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_skills', to='business_skill.validskill')),
            ],
            options={
                'unique_together': {('valid_skill', 'business_profile')},
            },
        ),
    ]
