# Generated by Django 3.1 on 2022-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
