# Generated by Django 3.1 on 2022-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_skill', '0002_skilltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='validskill',
            name='tag',
            field=models.ManyToManyField(related_name='valid_skills', to='business_skill.SkillTag'),
        ),
    ]
