# Generated by Django 3.1 on 2022-03-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('notif_type', models.CharField(max_length=200)),
                ('target_id', models.PositiveIntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_notif', to='system_notification.systemnotification')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_notifs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sen_notifs', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_obj', to='contenttypes.contenttype')),
            ],
        ),
    ]
